import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { latestVersionTag } from './latest-version-tag';

/**
 * Writes the current version tag into a generated TypeScript module.
 *
 * The esbuild based application builder has no equivalent of the webpack
 * `DefinePlugin` that used to inject the `VERSION` global, and `define` in
 * project.json only takes static values. Generating a tiny module before the
 * build keeps the tag a build time constant without a custom bundler config.
 *
 * Usage: tsx write-version-tag.ts <cdk-deployed|non-cdk-deployed> <outFile>
 */
function main(): void {
  const [prefix, outFile] = process.argv.slice(2);
  if (!prefix || !outFile) {
    throw new Error(
      'Usage: write-version-tag.ts <cdk-deployed|non-cdk-deployed> <outFile>'
    );
  }

  const versionTag = latestVersionTag(prefix);
  const contents = `// GENERATED by tools/version-handling/write-version-tag.ts - do not edit.
export const versionTag = '${versionTag}';
`;

  // Keep the file byte identical when nothing changed so watch builds and the
  // Nx cache are not invalidated on every run.
  let current: string | undefined;
  try {
    current = readFileSync(outFile, 'utf8');
  } catch {
    current = undefined;
  }
  if (current === contents) {
    console.log(`version tag unchanged (${versionTag})`);
    return;
  }

  mkdirSync(dirname(outFile), { recursive: true });
  writeFileSync(outFile, contents);
  console.log(`version tag ${versionTag} -> ${outFile}`);
}

main();
