import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve, sep } from 'node:path';
import { latestVersionTag } from './latest-version-tag';

/**
 * Writes the current version tag into a generated TypeScript module.
 *
 * The esbuild based application builder has no equivalent of the webpack
 * `DefinePlugin` that used to inject the `VERSION` global, and `define` in
 * project.json only takes static values. Generating a tiny module before the
 * build keeps the tag a build time constant without a custom bundler config.
 *
 * Usage: tsx write-version-tag.ts <cdk-deployed|non-cdk-deployed> <outFile>
 * where <outFile> is relative to the workspace root.
 */

const DEPLOY_PREFIXES = ['cdk-deployed', 'non-cdk-deployed'] as const;
type DeployPrefix = (typeof DEPLOY_PREFIXES)[number];

const USAGE =
  'Usage: write-version-tag.ts <cdk-deployed|non-cdk-deployed> <outFile>';

function parsePrefix(value: string | undefined): DeployPrefix {
  // Returns a literal rather than the argument itself: the prefix reaches a
  // RegExp in latestVersionTag, so nothing may flow there from the command line.
  if (value === 'cdk-deployed') {
    return 'cdk-deployed';
  }
  if (value === 'non-cdk-deployed') {
    return 'non-cdk-deployed';
  }
  throw new Error(`Unknown deploy prefix "${value}". ${USAGE}`);
}

/**
 * Resolves the output path against the workspace root and refuses anything
 * that escapes it, so a stray argument cannot write outside the repository.
 */
function parseOutFile(value: string | undefined): string {
  if (!value) {
    throw new Error(USAGE);
  }
  const workspaceRoot = resolve(process.cwd());
  const outFile = resolve(workspaceRoot, value);
  if (!outFile.startsWith(workspaceRoot + sep)) {
    throw new Error(`Refusing to write outside the workspace: ${value}`);
  }
  return outFile;
}

function main(): void {
  const [prefixArg, outFileArg] = process.argv.slice(2);
  const prefix = parsePrefix(prefixArg);
  const outFile = parseOutFile(outFileArg);

  const versionTag = latestVersionTag(prefix);
  // Tags come from `git describe`, so escape before embedding them in a string
  // literal rather than trusting them to be identifier safe.
  const literal = versionTag.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
  const contents = `// GENERATED by tools/version-handling/write-version-tag.ts - do not edit.
export const versionTag = '${literal}';
`;

  // Keep the file byte identical when nothing changed so watch builds and the
  // Nx cache are not invalidated on every run.
  let current: string | undefined;
  try {
    current = readFileSync(outFile, 'utf8');
  } catch {
    current = undefined;
  }
  if (current === contents) {
    console.log(`version tag unchanged (${versionTag})`);
    return;
  }

  mkdirSync(dirname(outFile), { recursive: true });
  writeFileSync(outFile, contents);
  console.log(`version tag ${versionTag} -> ${outFile}`);
}

main();
