name: 'Install Dependencies'
description: 'Installs all dependencies for this repo to run'
inputs:
  run-scripts: # id of input
    description: 'run npm install with --no-scripts flag'
    required: false
    default: 'false'
  cypress:
    description: 'install cypress'
    required: false
    default: 'false'
  apt-packages:
    description: 'install packages needed to run tests'
    required: false
    default: 'false'

runs:
  using: composite

  steps:
    - name: Install ubuntu dependencies
      if: inputs.apt-packages == 'true'
      shell: bash
      run: ./.github/actions/install-deps/install-ubuntu-packages.sh
    - uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: npm
    - name: Cache Cypress Binary
      id: cache-cypress-binary
      if: inputs.cypress == 'true'
      uses: actions/cache@v3
      with:
        path: ${{ env.CYPRESS_CACHE_FOLDER }}
        key: cypress-binary-${{ hashFiles('package-lock.json') }}
      env:
        CYPRESS_CACHE_FOLDER: 'cache/cypress'
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: modules-${{ inputs.run-scripts == 'true' && 'with' || 'ignore' }}-scripts-${{ inputs.cypress == 'true' && 'with' || 'ignore' }}-cypress-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' && inputs.cypress == 'false'
      shell: bash
      run: |
        npm install --ignore-scripts=${{ inputs.run-scripts == 'false' }}
      env:
        CYPRESS_INSTALL_BINARY: 0
        CYPRESS_CACHE_FOLDER: 'cache/cypress'

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' && inputs.cypress != 'false'
      shell: bash
      run: |
        npm install --ignore-scripts=${{ inputs.run-scripts == 'false' }}
      env:
        CYPRESS_CACHE_FOLDER: 'cache/cypress'

    - name: Install binaries
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        npm install @nx/nx-linux-x64-gnu
      env:
        CYPRESS_CACHE_FOLDER: 'cache/cypress'
