name: 'Install Dependencies'
description: 'Installs all dependencies for this repo to run'
inputs:
  run-scripts: # id of input
    description: 'run npm install with --no-scripts flag'
    required: false
    default: 'false'
  browser:
    description: 'install browser and playwright dependencies'
    required: false
    default: 'false'
  apt-packages:
    description: 'install packages needed to run tests'
    required: false
    default: 'false'

runs:
  using: composite

  steps:
    - name: Install ubuntu dependencies
      if: inputs.apt-packages == 'true'
      shell: bash
      run: ./.github/actions/install-deps/install-ubuntu-packages.sh

    - uses: actions/setup-node@v6
      with:
        node-version-file: '.nvmrc'
        cache: npm

    - name: Workaround gl build (force include uintptr_t definition)
      shell: bash
      run: |
        # stdint.h funktioniert für C und C++ (uintptr_t); cstdint würde beim C-Compiler fehlschlagen
        echo 'CXXFLAGS=-include stdint.h' >> $GITHUB_ENV
        echo 'CPPFLAGS=-include stdint.h' >> $GITHUB_ENV
        echo 'Applied CXXFLAGS workaround (-include stdint.h) for gl angleutils uintptr_t build failure'

    - name: Cache Playwright binaries
      id: cache-playwright-binary
      if: inputs.browser == 'true'
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: playwright-binary-${{ hashFiles('package-lock.json') }}

    # WICHTIG: npm ci muss IMMER laufen. Vorheriger Zustand übersprang Installation bei Cache-Hit -> Nx konnte nicht gefunden werden.
    - name: Install dependencies
      shell: bash
      run: |
        npm ci --ignore-scripts=${{ inputs.run-scripts == 'false' }}

    - name: Install Playwright browsers (only if needed)
      if: inputs.browser == 'true' && steps.cache-playwright-binary.outputs.cache-hit != 'true'
      shell: bash
      run: |
        sudo npx playwright install --with-deps
