name: 'Install Dependencies'
description: 'Installs all dependencies for this repo to run'
inputs:
  run-scripts: # id of input
    description: 'run pnpm install with --no-scripts flag'
    required: false
    default: 'false'
  cypress:
    description: 'install cypress and playwright dependencies'
    required: false
    default: 'false'
  apt-packages:
    description: 'install packages needed to run tests'
    required: false
    default: 'false'

runs:
  using: composite

  steps:
    - name: Install ubuntu dependencies
      if: inputs.apt-packages == 'true'
      shell: bash
      run: ./.github/actions/install-deps/install-ubuntu-packages.sh
    - uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: pnpm

    - id: cache-cypress-binary
      if: inputs.cypress == 'true'
      uses: actions/cache@v4
      with:
        path: ${{ env.CYPRESS_CACHE_FOLDER }}
        key: cypress-binary-${{ hashFiles('pnpm-lock.yaml') }}
    - name: Cache Playwright binaries
      id: cache-playwright-binary
      if: inputs.cypress == 'true'
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: playwright-binary-${{ hashFiles('pnpm-lock.yaml') }}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' && inputs.cypress == 'false'
      shell: bash
      run: |
        pnpm i --ignore-scripts=${{ inputs.run-scripts == 'false' }}
      env:
        CYPRESS_INSTALL_BINARY: 0

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' && inputs.cypress != 'false'
      shell: bash
      run: |
        pnpm i --ignore-scripts=${{ inputs.run-scripts == 'false' }}
        npx playwright install --with-deps
