export * from './lib/model/glsl-code.types';
export * from './lib/model/uniforms';
export * from './lib/model/mesh';
export * from './lib/model/plane-geometry';
export * from './lib/model/scene';
export * from './lib/model/shader-material';
export * from './lib/model/webgl2-renderer';
export * from './lib/model/uniforms';
export * from './lib/model/color.material';
export { default as defaultVertexShader } from './lib/model/shaders/default-vertex-shader.glsl';
export { default as defaultFragmentShader } from './lib/model/shaders/default-fragment-shader.glsl';
