name: Bump Version
on:
  workflow_run:
    workflows: [ ci² ]
    types: [ completed ]
    branches:
      - main
    tags-ignore:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Version bump and tag release
        if: !contains(github.event.workflow_run.head_commit.message, 'chore(release):')
        run: |
          echo 'Normal commit ${{ toJSON(github.event.workflow_run.head_commit.message) }}'
      - name: Info no run for release commits
        if: contains(github.event.workflow_run.head_commit.message, 'chore(release):')
        run: |
          echo "Not running for release commits ${{ toJSON(github.event.workflow_run.head_commit.message) }}"

