name: Bump Version
on:
  workflow_run:
    workflows: [ ci² ]
    types: [ completed ]
    branches:
      - main
    tags-ignore:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && !contains(github.event.workflow_run.head_commit.message, 'chore(release):') }}
    steps:
      - name: Version bump and tag release
        run: echo '${{ toJSON(github.event.workflow_run.head_commit.message) }}'
        # uses: ad-m/github-push-action@v0.6.0

