name: ci²

on:
  push:
    branches:
      - main
  pull_request:
    # The branches below must be a subset of the branches above
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') || startsWith(github.ref_name, 'renovate-github-sh') }}

env:
  HUSKY: 0
  NODE_OPTIONS: '--max_old_space_size=4096'
  NX_BRANCH: ${{ github.event.number || github.ref_name }}
  NX_CLOUD_DISTRIBUTED_EXECUTION: 'true'
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_DASHBOARD_KEY }}
  CYPRESS_CACHE_FOLDER: '~/.cache/cypress'
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  verify:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: 'Checkout branch'
        if: ${{ github.event_name != 'pull_request' }}
        with:
          fetch-depth: 0

      - uses: actions/checkout@v4
        name: 'Checkout [pr]'
        if: ${{ github.event_name == 'pull_request' }}
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Install Deps
        uses: ./.github/actions/install-deps
        with:
          cypress: true

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4

      - name: print affected base and head info
        run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"
          npx nx show projects --affected $( $RUNNER_DEBUG && echo '--verbose' )

      - run: npx nx-cloud start-ci-run
      - name: Run verification
        uses: JamesHenry/parallel-bash-commands@v1.0
        with:
          cmd1: npx nx affected --target=build --parallel=1 $( $RUNNER_DEBUG && echo '--verbose' )
          cmd2: npx nx affected --target=test --parallel=1 --code-coverage $( $RUNNER_DEBUG && echo '--verbose' )
          cmd3: npx nx affected --target=test-integration --parallel=1 --code-coverage $( $RUNNER_DEBUG && echo '--verbose' )
          cmd4: npx nx affected --target=lint --parallel=4 $( $RUNNER_DEBUG && echo '--verbose' )
          cmd5: npx nx affected --target=component-test --parallel=1 $( $RUNNER_DEBUG && echo '--verbose' )
          cmd6: npx -c \"nx affected --target=e2e --parallel=1 --configuration=ci $( $RUNNER_DEBUG && echo '--verbose' ) -- ${{!contains(github.event_name, 'pull_request') && '--record=true' || ''}}\"
      - run: npx nx-cloud stop-all-agents
        if: ${{ always() }}
      - name: Tag main branch if all jobs succeed
        if: ${{ github.ref_name == 'main' }}
        uses: nrwl/nx-tag-successful-ci-run@v1

      - name: Report Codecov
        if: github.ref_name == 'main' && hashFiles('coverage/**/*') != ''
        uses: codecov/codecov-action@v4-beta
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          fail_ci_if_error: true
          verbose: true

  agents:
    name: Nx Cloud Agents
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        agent: [1, 2, 3, 4]
    steps:
      - uses: actions/checkout@v4
        name: 'Checkout branch'
        if: ${{ github.event_name != 'pull_request' }}
        with:
          fetch-depth: 0
      - uses: actions/checkout@v4
        name: 'Checkout [pr]'
        if: ${{ github.event_name == 'pull_request' }}
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Install Deps
        uses: ./.github/actions/install-deps
        with:
          cypress: true
          apt-packages: true
          run-scripts: true

      - name: Start Nx Agent ${{ matrix.agent }}
        run: npx nx-cloud start-agent

  trigger-release:
    uses: ./.github/workflows/trigger-release.yml
    secrets: inherit
    needs: verify
    if: ${{ success() && !contains(github.event.head_commit.message, 'chore(release):') && github.ref_name == 'main' }}
