name: CI
on:
  push:
    branches:
      - main
  pull_request:

env:
  NODE_VERSION: '16'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: WolfSoko/nrwl-ci/.github/workflows/nx-cloud-main.yml@v0.2.1
    with:
      node-version: ${{ github.env.NODE_VERSION }}
      install-command: |
        echo 'Install packages to compile node_modules gl with node-gyp'
        sudo apt-get update -y
        sudo apt-get install xserver-xorg-dev libxi-dev libxext-dev -y
        npm ci
      parallel-commands: |
        npx nx workspace-lint
        npx nx format:check
      parallel-commands-on-agents: |
        npx nx affected --target=lint --parallel
        npx nx affected --target=test --parallel --code-coverage
        npx nx affected --target=build --parallel
        npx nx affected --target=e2e --parallel
  agents:
    name: Nx Cloud - Agents
    uses: WolfSoko/nrwl-ci/.github/workflows/nx-cloud-agents.yml@v0.2.1
    with:
      node-version: ${{ github.env.NODE_VERSION }}
      install-command: |
        echo 'Install packages to compile node_modules gl with node-gyp'
        sudo apt-get update -y
        sudo apt-get install xserver-xorg-dev libxi-dev libxext-dev -y
        npm ci
      number-of-agents: 7
