name: Create release
on:
  push:
    # Pattern matched against refs/tags
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  issues: write
  contents: write

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  HUSKY: 0

jobs:
  release:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 50

      - name: Install Deps
        uses: ./.github/actions/install-deps
        with:
          apt-packages: 'true'
          run-scripts: 'true'

      - name: create sentry release version
        id: sentry-version
        run: |
          SENTRY_VERSION="angular-examples@${{ github.ref_name }}"
          echo "Sentry version: ${SENTRY_VERSION}"
          echo "sentry-version=${SENTRY_VERSION}" >> $GITHUB_ENV

      - name: Build
        run: npx nx run-many -t="build" -c="production" --projects="tag:app"

      - name: ZIP-files for release
        uses: vimtor/action-zip@v1
        with:
          files: dist version.json
          recursive: false
          dest: release.zip

      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.RELEASE_GH_TOKEN }}'
          prerelease: false
          files: release.zip

      - name: Create Sentry Release
        uses: getsentry/action-release@v3
        with:
          version: ${{ env.sentry-version }}
          sourcemaps: 'dist/apps'
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: 'wolsok'
          SENTRY_PROJECT: 'angular-examples'

      - name: Create Issue on Failure
        if: failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueTitle = 'bug(release): create release pipeline failed';
            const issueBody = 'GitHub [create release workflow](https://github.com/WolfSoko/wol-sok-mono/actions/workflows/release.yml) failed';
            const labels = ['bug'];
            const assignees = [context.actor];

            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
              assignees: assignees,
              labels: labels
            });
