name: Test waiting
on:
  push:
    tags:
      - '*'

jobs:
  trigger-waiting:
    environment: aws
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ github.ref }}"
          echo "${{ github.ref_name }}"
          echo "${{ github.sha }}"

      - name: 'trigger-release:ci²-success'
        run: echo "TRIGGER"
